### YamlMime:QSharpType
uid: microsoft.quantum.canon.compose
name: Compose
type: function
namespace: microsoft.quantum.canon
summary: >-
  Devolve a composição de duas funções.


  Tendo em conta duas funções $f$ e $g$, devolve uma nova função que representa $f \circ g$.
syntax: "function Compose (outer : ('U -> 'V), inner : ('T -> 'U)) : ('T -> 'V)"
input:
  content: "(outer : ('U -> 'V), inner : ('T -> 'U))"
  types:
  - name: outer
    summary: A segunda função a ser aplicada.
    isFunction: true
    input:
      types:
      - uid: "'U"
        isLocal: true
    output:
      types:
      - uid: "'V"
        isLocal: true
  - name: inner
    summary: A primeira função a ser aplicada.
    isFunction: true
    input:
      types:
      - uid: "'T"
        isLocal: true
    output:
      types:
      - uid: "'U"
        isLocal: true
output:
  content: ('T -> 'V)
  types:
  - summary: Uma nova função $h$ tal que para todas as entradas $x$, $f(g(x)= h(x)$.
    isFunction: true
    input:
      types:
      - uid: "'T"
        isLocal: true
    output:
      types:
      - uid: "'V"
        isLocal: true
typeParameters:
- uid: "'T"
  summary: O tipo de entrada da primeira função a aplicar.
- uid: "'U"
  summary: O tipo de saída da primeira função a aplicar e o tipo de entrada da segunda função a aplicar.
- uid: "'V"
  summary: O tipo de saída da segunda função a aplicar.
metadata:
  ms.openlocfilehash: f2e4d8d10e8113101a5d0ec1f37f8bb7cd0945c0
  ms.sourcegitcommit: 685a8ab16d7e6a25e63a168d6e7c385fa6e876cc
  ms.translationtype: MT
  ms.contentlocale: pt-PT
  ms.lasthandoff: 09/29/2020
  ms.locfileid: "91467176"
