### YamlMime:QSharpType
uid: microsoft.quantum.canon.compose
name: Compose
type: function
namespace: Microsoft.Quantum.Canon
summary: >-
  Devolve a composição de duas funções.


  Tendo em conta duas funções $f$ e $g$, devolve uma nova função representando $f \circ g$.
syntax: "function Compose (outer : ('U -> 'V), inner : ('T -> 'U)) : ('T -> 'V)"
input:
  content: "(outer : ('U -> 'V), inner : ('T -> 'U))"
  types:
  - name: outer
    summary: A segunda função a aplicar.
    isFunction: true
    input:
      types:
      - uid: "'U"
        isLocal: true
    output:
      types:
      - uid: "'V"
        isLocal: true
  - name: inner
    summary: A primeira função a aplicar.
    isFunction: true
    input:
      types:
      - uid: "'T"
        isLocal: true
    output:
      types:
      - uid: "'U"
        isLocal: true
output:
  content: ('T -> 'V)
  types:
  - summary: Uma nova função $h$ de tal forma que para todas as inputs $x$, $f (g(x)) = h(x)$.
    isFunction: true
    input:
      types:
      - uid: "'T"
        isLocal: true
    output:
      types:
      - uid: "'V"
        isLocal: true
typeParameters:
- uid: "'T"
  summary: O tipo de entrada da primeira função a aplicar.
- uid: "'U"
  summary: O tipo de saída da primeira função a aplicar e o tipo de entrada da segunda função a aplicar.
- uid: "'V"
  summary: O tipo de saída da segunda função a aplicar.
metadata:
  ms.openlocfilehash: 44296db92d6261fc8aba843346700bf8e22663bb
  ms.sourcegitcommit: ca5015fed409eaf0395a89c2e4bc6a890c360aa2
  ms.translationtype: MT
  ms.contentlocale: pt-PT
  ms.lasthandoff: 01/29/2020
  ms.locfileid: "76871554"
